### ISSUE TITLE
Promises?

### ISSUE THREAD

**Issue by brettz9** [tarranjones/macOS-defaults#2]
Hi,

Was wondering what you thought about using Promises instead of (or in addition to) callbacks?

**Comment by brettz9** [comment]
FWIW, in my "class" branch, I've been working on a major refactoring which is more hard-coded given the different needs of each method. Besides returning promises for the async method, I made a parser (with tests) for the property list strings returned by `defaults` commands like `defaults read` and `defaults find` to convert them to JSON. I've also added the ability to add JSON arrays/objects, Uint8Array binary data, etc. I need more tests (particularly for the modifying operations), but thought I'd mention it.

**Comment by brettz9** [comment]
FWIW, that branch has now stabilized... I have a bunch of tests now... Still haven't used in the real world, but I could make a PR if you were interested (but it is basically a complete rewrite as I needed specific handling for each method)...

**Comment by brettz9** [comment]
I've pushed now to your `master`. Would you like to look over and see if you have any issues? It'd be great to have an npm release if things look ok to you...

**Comment by tarranjones** [comment]
Hi @brettz9, Thank you so much for your input. i will take a look at this tomorrow and publish a new release to npm.

**Comment by brettz9** [comment]
I know it was a large commit, but just a friendly ping...
